site_name = "client.com"
uid = 1001
gid = 1001
socket = "/var/run/axonasp/client.com.sock"
config_file = "/home/client.com/config/axonasp.toml"
app_path = "/home/client.com/public_html/"
memory_limit_mb = 128
max_restarts=3
tmp_dir = "/home/client.com/tmp"