<%@ Language=VBScript %>
<%
Option Explicit

Dim mode
mode = LCase(Trim(CStr(Request.QueryString("mode"))))

If mode = "image" Then
    Call RenderImageBinary()
Else
    Call RenderHtmlTestPage()
End If

Sub RenderImageBinary()
    On Error Resume Next

    Dim img, bytes, contentType
    Set img = Server.CreateObject("G3IMAGE")

    img.NewContext 640, 260
    img.SetHexColor "#0f172a"
    img.Clear

    img.SetHexColor "#14b8a6"
    img.DrawRoundedRectangle 20, 20, 600, 220, 18
    img.Fill

    img.SetHexColor "#ffffff"
    img.DrawCircle 120, 130, 62
    img.Fill

    img.SetHexColor "#0f172a"
    img.DrawStringAnchored "G3IMAGE runtime test", 360, 118, 0.5, 0.5
    img.DrawStringAnchored "BinaryWrite + Cleanup", 360, 150, 0.5, 0.5

    bytes = img.RenderContent("png")
    contentType = CStr(img.LastMimeType)
    If contentType = "" Then contentType = "image/png"

    ' Explicit release before flushing response
    img.Close
    Set img = Nothing

    If Err.Number <> 0 Then
        Response.ContentType = "text/plain"
        Response.Write "G3IMAGE render failed: " & Err.Description
        Response.End
    End If

    Response.ContentType = contentType
    Response.BinaryWrite bytes
    Response.End
End Sub

Sub RenderHtmlTestPage()
    On Error Resume Next

    Dim img, beforeClose, afterClose, beforeMime, afterMime
    Set img = Server.CreateObject("G3IMAGE")

    img.NewContext 32, 32
    beforeClose = CStr(img.HasContext)
    beforeMime = CStr(img.LastMimeType)

    img.Close

    afterClose = CStr(img.HasContext)
    afterMime = CStr(img.LastMimeType)

    Set img = Nothing
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>G3IMAGE Library Test</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 24px; line-height: 1.45; }
        .box { border: 1px solid #ddd; border-radius: 8px; padding: 14px; margin-bottom: 16px; }
        .ok { color: #0f766e; }
        .bad { color: #b91c1c; }
        code { background: #f3f4f6; padding: 2px 5px; border-radius: 4px; }
        img { max-width: 100%; border: 1px solid #ddd; border-radius: 8px; }
    </style>
</head>
<body>
    <h1>G3IMAGE Integration Test</h1>

    <div class="box">
        <h3>Resource cleanup check</h3>
        <p>HasContext before Close: <code><%=beforeClose%></code></p>
        <p>HasContext after Close: <code><%=afterClose%></code></p>
        <p>LastMimeType before Close: <code><%=Server.HTMLEncode(beforeMime)%></code></p>
        <p>LastMimeType after Close: <code><%=Server.HTMLEncode(afterMime)%></code></p>
        <% If LCase(beforeClose) = "true" And LCase(afterClose) = "false" Then %>
            <p class="ok"><strong>PASS:</strong> Context reference was released.</p>
        <% Else %>
            <p class="bad"><strong>FAIL:</strong> Context was not released as expected.</p>
        <% End If %>
    </div>

    <div class="box">
        <h3>Rendered output (binary)</h3>
        <p>This image is generated by <code>G3IMAGE</code> and streamed via <code>Response.BinaryWrite</code>.</p>
        <img src="test_g3image.asp?mode=image&ts=<%=Timer()%>" alt="G3IMAGE output" />
    </div>

    <% If Err.Number <> 0 Then %>
        <div class="box bad">
            <strong>Error:</strong> <%=Server.HTMLEncode(Err.Description)%>
        </div>
    <% End If %>
</body>
</html>
<%
End Sub
%>
