<%@ Language="JavaScript" %>
<%
/* Auto-generated by G3pix AxonLive Visual Builder */
var AxonLive = Server.CreateObject("G3AXONLIVE");
AxonLive.InitPage();

var sessionID = Session.SessionID;

// Restore persisted state from server-side store (survives across async re-executions)
var _raw_lblCounter_val = AxonLive.GetComponentProperty(sessionID, "lblCounter", "val");
var lblCounter_val = 0;
if (_raw_lblCounter_val !== "" && _raw_lblCounter_val !== null && !isNaN(parseInt(_raw_lblCounter_val, 10))) {
    lblCounter_val = parseInt(_raw_lblCounter_val, 10);
}

if (AxonLive.IsAsyncRequest) {
    var compID  = AxonLive.EventComponentID;
    var evtName = AxonLive.EventName;

    switch (compID) {
        case "axl_button_3":
            if (evtName === "onclick") {
                    lblCounter_val = lblCounter_val + 1;
            }
            break;

    }

    // Persist updated state so the next async call can restore it
    AxonLive.SetComponentProperty(sessionID, "lblCounter", "val", String(lblCounter_val));

    AxonLive.RegisterComponent("lblCounter", '<span id="lblCounter">'+lblCounter_val+'</span>');

    AxonLive.EndAsyncResponse();
}
%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AxonLive Application</title>
        <link rel="stylesheet" href="/css/axonasp.css">
    </head>

    <body>

        <div id="main-container">
            <div id="content">
                <span id="lblCounter">Contador</span>
                <button id="axl_button_3" class="btn btn-primary" data-g3al-id="axl_button_3" data-g3al-event="click"
                    data-g3al-event-name="onclick">Click Me</button>

            </div>
        </div>
        <script src="/axonlive/g3axonlive.js"></script>
        <script>
            G3AxonLive.init('<%=Server.HTMLEncode(Session.SessionID)%>');
        </script>
    </body>

</html>