<%@ Language="JavaScript" %>
<%
/* Auto-generated by G3pix AxonLive Visual Builder */
var AxonLive = Server.CreateObject("G3AXONLIVE");
AxonLive.InitPage();

var sessionID = Session.SessionID;


if (AxonLive.IsAsyncRequest) {
    var compID  = AxonLive.EventComponentID;
    var evtName = AxonLive.EventName;

    switch (compID) {
        case "axl_link_2":
            if (evtName === "onclick") {
                // Logic for onclick
                axl_modal_3.style.display='none';
            }
            break;

    }



    AxonLive.RegisterComponent("axl_link_2", '<div id="axl_link_2">Link Text</div>');
    AxonLive.RegisterComponent("axl_modal_3", '<div id="axl_modal_3">This is an alert.</div>');

    AxonLive.EndAsyncResponse();
}
%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AxonLive Application</title>
        <link rel="stylesheet" href="/css/axonasp.css">
    </head>

    <body>

        <div id="main-container">
            <div id="content">
                <div>Raw HTML</div>
                <a href="#" id="axl_link_2" data-g3al-id="axl_link_2" data-g3al-event="click"
                    data-g3al-event-name="onclick">Link Text</a>
                <div id="axl_modal_3" class="window">
                    <div class="window-header"><span>Notice</span><span style="cursor:pointer"
                            onclick="this.parentNode.parentNode.style.display='none'">X</span></div>
                    <div class="window-body">
                        <div class="alert alert-success">This is an alert.</div>
                        <div style="margin-top: 15px; display:flex; justify-content:flex-end; gap:5px;">
                            <button class="btn btn-primary"
                                onclick="this.parentNode.parentNode.parentNode.style.display='none';">OK</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <script src="/axonlive/g3axonlive.js"></script>
        <script>
            G3AxonLive.init('<%=Server.HTMLEncode(Session.SessionID)%>');
        </script>
    </body>

</html>